# This is a basic workflow to help you get started with Actions

name: CI/CD (Build and Deploy)

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the matser branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# This workflow contains two jobs called "build" and "deploy"
jobs:

  # JOB 1
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      # contents: read
      attestations: write
      
    steps:
    
    - name: Checkout master branch
      uses: actions/checkout@v3
      
    - name: Install Node.js 18.x & NPM
      uses: actions/setup-node@v3 #this installs node and npm for us
      with:
        node-version: '18.x'
        
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    # Install latest npm due issue with one of the packages
    - name: Install latest npm
      run: npm i -g npm@latest
      
    - name: Build
      run:  |
        npm install
        npm run-script deploy
        
    - name: archive build
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: deployable_artifacts
        path: dist
        

  # JOB 2
  attest:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: deployable_artifacts
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: deployable_artifacts

  # JOB 3
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v1
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: deployable_artifacts
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: deployable_artifacts
